version: "3.3"
services:
  owtf:
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["/usr/bin/wait-for-it.sh", "db:5432", "--", "owtf"]
    environment:
      - DOCKER=1
      - POSTGRES_USER=owtf_db_user
      - POSTGRES_PASSWORD=jgZKW33Q+HZk8rqylZxaPg1lbuNGHJhgzsq3gBKV32g=
      - POSTGRES_DB=owtf_db
    ports:
      - 8008:8008
      - 8010:8010
      - 8009:8009
    depends_on:
      - db
    volumes:
      - ..:/owtf
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=owtf_db_user
      - POSTGRES_PASSWORD=jgZKW33Q+HZk8rqylZxaPg1lbuNGHJhgzsq3gBKV32g=
      - POSTGRES_DB=owtf_db
